image: node:12.20.1

pipelines:
  branches:
    release/live_deploy: #please create this branch first time before start test_deploy.
      - step:
          name: Yarn run build
          caches:
            - node
          script:
            - node
            - yarn
            - rm .env && cp .env.production_onlinux .env && cat .env
            - yarn run build
            - ls dist
          artifacts: # Share files to after step.
            - dist/**
      - step:
          name: Deploy to EC2 by SSH
          caches:
            - composer
          script:
            - pipe: atlassian/rsync-deploy:0.3.1
              variables:
                USER: $AWS_EC2_USER
                SERVER: $AWS_EC2_HOST
                REMOTE_PATH: '/usr/share/nginx/club_ichijo/client_front/'
                LOCAL_PATH: 'dist/'
                EXTRA_ARGS: '--exclude-from=deployment-exclude-list.txt --ignore-times'
                DEBUG: 'true'
                SSH_PORT: $AWS_EC2_PORT
    release/test_deploy: #please create this branch first time before start test_deploy.
      - step:
          name: Yarn run build
          caches:
            - node
          script:
            - node
            - yarn
            - rm .env && cp .env.staging_onlinux .env && cat .env
            - yarn run build
            - ls dist
          artifacts: # Share files to after step.
            - dist/**
      - step:
          name: Deploy to EC2 by SSH
          caches:
            - composer
          script:
            - pipe: atlassian/rsync-deploy:0.3.1
              variables:
                USER: $AWS_EC2_USER
                SERVER: $AWS_EC2_HOST
                REMOTE_PATH: '/usr/share/nginx/club_ichijo/client_front_test/'
                LOCAL_PATH: 'dist/'
                EXTRA_ARGS: '--exclude-from=deployment-exclude-list.txt --ignore-times'
                DEBUG: 'true'
                SSH_PORT: $AWS_EC2_PORT
   